name: Sync to Gitee

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to Gitee
        uses: wearerequired/git-mirror@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_TOKEN }}
        with:
          # 替换为你的 Gitee 仓库地址
          destination-repo: "git@gitee.com:wwhhaha/area.git"
          
      - name: Notify Gitee
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"access_token":"${{ secrets.GITEE_TOKEN }}", "ref":"master"}' \
          "https://gitee.com/api/v5/repos/your_username/your_repo/trigger/pipeline"
