name: Sync from Gitee

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Setup Git identity
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "github-actions@github.com"
          
      - name: Add Gitee remote
        run: |
          # 添加 Gitee 远程仓库（不包含认证信息）
          git remote add gitee https://gitee.com/wwhhaha/area.git
          
          # 单独配置认证
          git config credential.helper 'store --file=.git/credentials'
          echo "https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com" > .git/credentials
          
      - name: Fetch Gitee changes
        run: git fetch gitee
          
      - name: Merge changes
        run: |
          # 合并 Gitee 的 master 分支
          git merge gitee/master --allow-unrelated-histories --strategy-option theirs
          
          # 解决可能的冲突（接受所有更改）
          git checkout --theirs . || true
          git add -A
          git commit -m "Merge from Gitee" || true
          
      - name: Push to GitHub
        run: git push origin HEAD:master
